[providers]
python = "3.13"

[providers.system]
packages = ["postgresql-client"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
